stderr of test 'segfault_in_descendant_step.SF-1744590.unpack_docs` in directory 'tests/BugTracker` itself:


# 16:23:55 >  
# 16:23:55 >  Mtimeout -timeout 60 /usr/bin/python segfault_in_descendant_step.SF-1744590.unpack_docs.py segfault_in_descendant_step.SF-1744590.unpack_docs 
# 16:23:55 >  


# 16:23:55 >  
# 16:23:55 >  Done.
# 16:23:55 >  

